# Generated by Django 6.0.5 on 2026-05-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payout_status',
            field=models.CharField(choices=[('NOT_READY', 'Not ready'), ('READY_FOR_PAYOUT', 'Ready for payout'), ('PAID_OUT', 'Paid out')], default='NOT_READY', max_length=24),
        ),
    ]

