# Generated by Django 6.0.5 on 2026-05-10 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('employer_type', models.CharField(choices=[('HOUSEHOLD', 'Household'), ('BUSINESS', 'Business'), ('PROPERTY', 'Property / landlord'), ('OTHER', 'Other')], default='HOUSEHOLD', max_length=20)),
                ('primary_location_label', models.CharField(blank=True, max_length=80)),
                ('primary_area', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('APP', 'App'), ('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('trust_status', models.CharField(choices=[('NEW', 'New'), ('PROFILE_STARTED', 'Profile started'), ('READY_FOR_BOOKING', 'Ready for booking'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended')], default='NEW', max_length=24)),
                ('profile_completion_percent', models.PositiveSmallIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('notes_for_helper', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='employers.employerprofile')),
            ],
            options={
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerServicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, choices=[('once_off_cleaning', 'Once-off cleaning'), ('recurring_help', 'Recurring help'), ('office_cleaning', 'Office cleaning'), ('laundry', 'Laundry'), ('cooking', 'Cooking'), ('childcare', 'Childcare')], max_length=40)),
                ('service_frequency', models.CharField(blank=True, choices=[('once_off', 'Once-off'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('as_needed', 'As needed')], max_length=30)),
                ('preferred_day', models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('FLEXIBLE', 'Flexible')], max_length=10)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration_hours', models.PositiveSmallIntegerField(default=4)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_preferences', to='employers.employerprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerTrustSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('PHONE_VERIFIED', 'Phone verified'), ('LOCATION_CAPTURED', 'Location captured'), ('SERVICE_NEED_CAPTURED', 'Service need captured'), ('BOOKING_HISTORY', 'Booking history'), ('PAYMENT_READINESS', 'Payment readiness')], max_length=40)),
                ('status', models.CharField(choices=[('NOT_PROVIDED', 'Not provided'), ('READY', 'Ready'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_PROVIDED', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_signals', to='employers.employerprofile')),
            ],
            options={
                'ordering': ['signal_type'],
            },
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['is_active', 'is_profile_complete'], name='employers_e_is_acti_533eec_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['trust_status'], name='employers_e_trust_s_506eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['primary_area'], name='employers_e_primary_da8938_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['employer_type'], name='employers_e_employe_1b6454_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employertrustsignal',
            unique_together={('employer', 'signal_type')},
        ),
    ]
