# Generated by Django 6.0.5 on 2026-05-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('locations', '0001_locality_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerlocation',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_locations', to='locations.locality'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='primary_area_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_profiles', to='locations.locality'),
        ),
    ]
