# Generated by Django 6.0.5 on 2026-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_locality_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employers/profile_photos/%Y/%m/'),
        ),
    ]
