
SA_LOCALITIES = [
    # Gauteng — Ekurhuleni & east rand
    ("Benoni", "Gauteng", "suburb", "Ekurhuleni", 10),
    ("Boksburg", "Gauteng", "suburb", "Ekurhuleni", 10),
    ("Brakpan", "Gauteng", "suburb", "Ekurhuleni", 15),
    ("Springs", "Gauteng", "suburb", "Ekurhuleni", 15),
    ("Germiston", "Gauteng", "suburb", "Ekurhuleni", 12),
    ("Alberton", "Gauteng", "suburb", "Ekurhuleni", 12),
    ("Kempton Park", "Gauteng", "suburb", "Ekurhuleni", 12),
    ("Edenvale", "Gauteng", "suburb", "Ekurhuleni", 14),
    ("Bedfordview", "Gauteng", "suburb", "Ekurhuleni", 18),
    ("Boksburg North", "Gauteng", "suburb", "Ekurhuleni", 25),
    ("Daveyton", "Gauteng", "suburb", "Ekurhuleni", 25),
    ("Duduza", "Gauteng", "suburb", "Ekurhuleni", 30),
    ("Katlehong", "Gauteng", "suburb", "Ekurhuleni", 20),
    ("Vosloorus", "Gauteng", "suburb", "Ekurhuleni", 22),
    ("Tembisa", "Gauteng", "suburb", "Ekurhuleni", 18),
    ("Olifantsfontein", "Gauteng", "suburb", "Ekurhuleni", 35),
    # Gauteng — Johannesburg
    ("Johannesburg", "Gauteng", "city", "City of Johannesburg", 5),
    ("Sandton", "Gauteng", "suburb", "City of Johannesburg", 8),
    ("Rosebank", "Gauteng", "suburb", "City of Johannesburg", 20),
    ("Randburg", "Gauteng", "suburb", "City of Johannesburg", 12),
    ("Roodepoort", "Gauteng", "suburb", "City of Johannesburg", 14),
    ("Soweto", "Gauteng", "suburb", "City of Johannesburg", 10),
    ("Diepsloot", "Gauteng", "suburb", "City of Johannesburg", 25),
    ("Midrand", "Gauteng", "suburb", "City of Johannesburg", 10),
    ("Alexandra", "Gauteng", "suburb", "City of Johannesburg", 22),
    ("Bryanston", "Gauteng", "suburb", "City of Johannesburg", 18),
    ("Fourways", "Gauteng", "suburb", "City of Johannesburg", 16),
    ("Florida", "Gauteng", "suburb", "City of Johannesburg", 24),
    ("Honeydew", "Gauteng", "suburb", "City of Johannesburg", 24),
    # Gauteng — Tshwane
    ("Pretoria", "Gauteng", "city", "City of Tshwane", 5),
    ("Centurion", "Gauteng", "suburb", "City of Tshwane", 10),
    ("Soshanguve", "Gauteng", "suburb", "City of Tshwane", 18),
    ("Mamelodi", "Gauteng", "suburb", "City of Tshwane", 18),
    ("Akasia", "Gauteng", "suburb", "City of Tshwane", 22),
    ("Menlyn", "Gauteng", "suburb", "City of Tshwane", 20),
    # Gauteng — West Rand
    ("Krugersdorp", "Gauteng", "suburb", "West Rand", 14),
    ("Randfontein", "Gauteng", "suburb", "West Rand", 20),
    ("Carletonville", "Gauteng", "town", "West Rand", 28),
    # Mpumalanga — border / highveld
    ("Nelspruit", "Mpumalanga", "city", "Mbombela", 10),
    ("Mbombela", "Mpumalanga", "city", "Mbombela", 12),
    ("Witbank", "Mpumalanga", "city", "Emalahleni", 12),
    ("Emalahleni", "Mpumalanga", "city", "Emalahleni", 14),
    ("Secunda", "Mpumalanga", "town", "Govan Mbeki", 18),
    ("Middelburg", "Mpumalanga", "town", "Steve Tshwete", 20),
    # North West
    ("Rustenburg", "North West", "city", "Rustenburg", 12),
    ("Potchefstroom", "North West", "city", "Potchefstroom", 16),
    ("Mahikeng", "North West", "city", "Mahikeng", 18),
    # Limpopo
    ("Polokwane", "Limpopo", "city", "Polokwane", 10),
    ("Tzaneen", "Limpopo", "town", "Greater Tzaneen", 22),
    # Free State
    ("Bloemfontein", "Free State", "city", "Mangaung", 8),
    ("Welkom", "Free State", "city", "Masilonyana", 18),
    # KwaZulu-Natal
    ("Durban", "KwaZulu-Natal", "city", "eThekwini", 5),
    ("Pietermaritzburg", "KwaZulu-Natal", "city", "Msunduzi", 10),
    ("Umhlanga", "KwaZulu-Natal", "suburb", "eThekwini", 12),
    ("Ballito", "KwaZulu-Natal", "suburb", "KwaDukuza", 16),
    ("Pinetown", "KwaZulu-Natal", "suburb", "eThekwini", 14),
    ("Amanzimtoti", "KwaZulu-Natal", "suburb", "eThekwini", 18),
    ("Chatsworth", "KwaZulu-Natal", "suburb", "eThekwini", 18),
    ("Phoenix", "KwaZulu-Natal", "suburb", "eThekwini", 20),
    ("Newcastle", "KwaZulu-Natal", "city", "Newcastle", 20),
    ("Richards Bay", "KwaZulu-Natal", "city", "uMhlathuze", 22),
    # Eastern Cape — Nelson Mandela Bay
    ("Gqeberha", "Eastern Cape", "city", "Nelson Mandela Bay", 5),
    ("Port Elizabeth", "Eastern Cape", "city", "Nelson Mandela Bay", 8),
    ("Kariega", "Eastern Cape", "city", "Nelson Mandela Bay", 10),
    ("Uitenhage", "Eastern Cape", "city", "Nelson Mandela Bay", 12),
    ("Despatch", "Eastern Cape", "town", "Nelson Mandela Bay", 14),
    ("Motherwell", "Eastern Cape", "suburb", "Nelson Mandela Bay", 12),
    ("Walmer", "Eastern Cape", "suburb", "Nelson Mandela Bay", 14),
    ("Summerstrand", "Eastern Cape", "suburb", "Nelson Mandela Bay", 14),
    ("Humewood", "Eastern Cape", "suburb", "Nelson Mandela Bay", 16),
    ("Newton Park", "Eastern Cape", "suburb", "Nelson Mandela Bay", 16),
    ("Greenacres", "Eastern Cape", "suburb", "Nelson Mandela Bay", 18),
    ("Lorraine", "Eastern Cape", "suburb", "Nelson Mandela Bay", 18),
    ("Charlo", "Eastern Cape", "suburb", "Nelson Mandela Bay", 20),
    ("Kabega Park", "Eastern Cape", "suburb", "Nelson Mandela Bay", 20),
    ("Bluewater Bay", "Eastern Cape", "suburb", "Nelson Mandela Bay", 22),
    ("Seaview", "Eastern Cape", "suburb", "Nelson Mandela Bay", 22),
    ("Colchester", "Eastern Cape", "suburb", "Nelson Mandela Bay", 24),
    ("Bethelsdorp", "Eastern Cape", "suburb", "Nelson Mandela Bay", 20),
    ("KwaNobuhle", "Eastern Cape", "suburb", "Nelson Mandela Bay", 22),
    ("Zwide", "Eastern Cape", "suburb", "Nelson Mandela Bay", 22),
    ("Gelvandale", "Eastern Cape", "suburb", "Nelson Mandela Bay", 24),
    ("Schauderville", "Eastern Cape", "suburb", "Nelson Mandela Bay", 26),
    # Eastern Cape — Buffalo City
    ("East London", "Eastern Cape", "city", "Buffalo City", 8),
    ("Mdantsane", "Eastern Cape", "suburb", "Buffalo City", 12),
    ("Gonubie", "Eastern Cape", "suburb", "Buffalo City", 14),
    ("Beacon Bay", "Eastern Cape", "suburb", "Buffalo City", 14),
    ("Cambridge", "Eastern Cape", "suburb", "Buffalo City", 16),
    ("Nahoon", "Eastern Cape", "suburb", "Buffalo City", 16),
    ("Vincent", "Eastern Cape", "suburb", "Buffalo City", 18),
    ("Quigney", "Eastern Cape", "suburb", "Buffalo City", 18),
    ("Berlin", "Eastern Cape", "suburb", "Buffalo City", 22),
    ("Bhisho", "Eastern Cape", "town", "Buffalo City", 20),
    # Eastern Cape — Kouga & Sarah Baartman (coast)
    ("Jeffreys Bay", "Eastern Cape", "town", "Kouga", 14),
    ("Humansdorp", "Eastern Cape", "town", "Kouga", 16),
    ("St Francis Bay", "Eastern Cape", "town", "Kouga", 18),
    ("Patensie", "Eastern Cape", "town", "Kouga", 28),
    ("Alexandria", "Eastern Cape", "town", "Ndlambe", 22),
    ("Port Alfred", "Eastern Cape", "town", "Ndlambe", 16),
    ("Kenton-on-Sea", "Eastern Cape", "town", "Ndlambe", 18),
    ("Boesmansriviermond", "Eastern Cape", "town", "Ndlambe", 26),
    # Eastern Cape — Amathole & OR Tambo
    ("Mthatha", "Eastern Cape", "city", "King Sabata Dalindyebo", 10),
    ("Libode", "Eastern Cape", "town", "King Sabata Dalindyebo", 24),
    ("Port St Johns", "Eastern Cape", "town", "Port St Johns", 22),
    ("Flagstaff", "Eastern Cape", "town", "Ingquza Hill", 28),
    ("King William's Town", "Eastern Cape", "town", "Buffalo City", 18),
    ("Qonce", "Eastern Cape", "town", "Buffalo City", 20),
    ("Butterworth", "Eastern Cape", "town", "Mnquma", 18),
    ("Dutywa", "Eastern Cape", "town", "Mbhashe", 24),
    ("Adelaide", "Eastern Cape", "town", "Walter Sisulu", 28),
    # Eastern Cape — Chris Hani & interior
    ("Queenstown", "Eastern Cape", "town", "Enoch Mgijima", 14),
    ("Komani", "Eastern Cape", "town", "Enoch Mgijima", 16),
    ("Sterkspruit", "Eastern Cape", "town", "Elundini", 26),
    ("Lady Frere", "Eastern Cape", "town", "Emalahleni", 28),
    ("Cofimvaba", "Eastern Cape", "town", "Intsika Yethu", 28),
    ("Cradock", "Eastern Cape", "town", "Dr Beyers Naudé", 20),
    ("Graaff-Reinet", "Eastern Cape", "town", "Dr Beyers Naudé", 18),
    ("Aberdeen", "Eastern Cape", "town", "Dr Beyers Naudé", 26),
    ("Somerset East", "Eastern Cape", "town", "Dr Beyers Naudé", 24),
    ("Aliwal North", "Eastern Cape", "town", "Maletswai", 22),
    ("Burgersdorp", "Eastern Cape", "town", "Walter Sisulu", 26),
    ("Barkly East", "Eastern Cape", "town", "Walter Sisulu", 30),
    # Eastern Cape — Makana & Sundays River
    ("Makhanda", "Eastern Cape", "town", "Makana", 14),
    ("Grahamstown", "Eastern Cape", "town", "Makana", 16),
    ("Kirkwood", "Eastern Cape", "town", "Sundays River Valley", 24),
    ("Addo", "Eastern Cape", "town", "Sundays River Valley", 26),
    # Western Cape
    ("Cape Town", "Western Cape", "city", "City of Cape Town", 5),
    ("Bellville", "Western Cape", "suburb", "City of Cape Town", 14),
    ("Khayelitsha", "Western Cape", "suburb", "City of Cape Town", 16),
    ("Mitchells Plain", "Western Cape", "suburb", "City of Cape Town", 16),
    ("Stellenbosch", "Western Cape", "town", "Stellenbosch", 14),
    ("Paarl", "Western Cape", "town", "Drakenstein", 16),
    ("George", "Western Cape", "city", "George", 18),
    ("Somerset West", "Western Cape", "suburb", "City of Cape Town", 18),
    ("Durbanville", "Western Cape", "suburb", "City of Cape Town", 20),
    # Northern Cape
    ("Kimberley", "Northern Cape", "city", "Sol Plaatje", 18),
    ("Upington", "Northern Cape", "city", "Kai !Garib", 24),
    # Eastern Cape — additional coverage for MongiKazi signup/search
    ('Mount Pleasant', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 18),
    ('Miramar', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 18),
    ('Mill Park', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 18),
    ('Parsons Hill', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 18),
    ('Mount Croix', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 20),
    ('Rowallan Park', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 20),
    ('Westering', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 20),
    ('Linton Grange', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 20),
    ('Theescombe', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 22),
    ('Sardinia Bay', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 24),
    ('New Brighton', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 20),
    ('KwaZakhele', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 20),
    ('KwaDwesi', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 22),
    ('Wells Estate', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 22),
    ('Redhouse', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 24),
    ('Kwanobuhle', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 22),
    ('KwaLanga', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 24),
    ('Rosedale', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 24),
    ('Kruisrivier', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 26),
    ('Swartkops', 'Eastern Cape', 'suburb', 'Nelson Mandela Bay', 24),
    ('Southernwood', 'Eastern Cape', 'suburb', 'Buffalo City', 16),
    ('Berea', 'Eastern Cape', 'suburb', 'Buffalo City', 16),
    ('Stirling', 'Eastern Cape', 'suburb', 'Buffalo City', 16),
    ('Baysville', 'Eastern Cape', 'suburb', 'Buffalo City', 18),
    ('Selborne', 'Eastern Cape', 'suburb', 'Buffalo City', 18),
    ('Amalinda', 'Eastern Cape', 'suburb', 'Buffalo City', 18),
    ('Abbotsford', 'Eastern Cape', 'suburb', 'Buffalo City', 20),
    ('Duncan Village', 'Eastern Cape', 'suburb', 'Buffalo City', 20),
    ('Scenery Park', 'Eastern Cape', 'suburb', 'Buffalo City', 20),
    ('Reeston', 'Eastern Cape', 'suburb', 'Buffalo City', 22),
    ('Nompumelelo', 'Eastern Cape', 'suburb', 'Buffalo City', 22),
    ('Dimbaza', 'Eastern Cape', 'town', 'Buffalo City', 24),
    ('Zwelitsha', 'Eastern Cape', 'town', 'Buffalo City', 22),
    ('Phakamisa', 'Eastern Cape', 'suburb', 'Buffalo City', 24),
    ('Alice', 'Eastern Cape', 'town', 'Raymond Mhlaba', 18),
    ('Fort Beaufort', 'Eastern Cape', 'town', 'Raymond Mhlaba', 18),
    ('Bedford', 'Eastern Cape', 'town', 'Raymond Mhlaba', 24),
    ('Hogsback', 'Eastern Cape', 'town', 'Raymond Mhlaba', 26),
    ('Seymour', 'Eastern Cape', 'town', 'Raymond Mhlaba', 28),
    ('Middledrift', 'Eastern Cape', 'town', 'Raymond Mhlaba', 28),
    ('Stutterheim', 'Eastern Cape', 'town', 'Amahlathi', 18),
    ('Keiskammahoek', 'Eastern Cape', 'town', 'Amahlathi', 24),
    ('Cathcart', 'Eastern Cape', 'town', 'Amahlathi', 24),
    ('Komga', 'Eastern Cape', 'town', 'Great Kei', 22),
    ('Kei Mouth', 'Eastern Cape', 'town', 'Great Kei', 22),
    ('Morgan Bay', 'Eastern Cape', 'town', 'Great Kei', 24),
    ('Haga Haga', 'Eastern Cape', 'town', 'Great Kei', 28),
    ('Chintsa', 'Eastern Cape', 'town', 'Great Kei', 20),
    ('Cintsa', 'Eastern Cape', 'town', 'Great Kei', 20),
    ('Peddie', 'Eastern Cape', 'town', 'Ngqushwa', 24),
    ('Hamburg', 'Eastern Cape', 'town', 'Ngqushwa', 26),
    ('Bathurst', 'Eastern Cape', 'town', 'Ndlambe', 22),
    ('Kleinemonde', 'Eastern Cape', 'town', 'Ndlambe', 24),
    ('Cannon Rocks', 'Eastern Cape', 'town', 'Ndlambe', 26),
    ('Alicedale', 'Eastern Cape', 'town', 'Makana', 24),
    ('Riebeek East', 'Eastern Cape', 'town', 'Makana', 28),
    ('Paterson', 'Eastern Cape', 'town', 'Sundays River Valley', 24),
    ('Jansenville', 'Eastern Cape', 'town', 'Dr Beyers Naudé', 26),
    ('Klipplaat', 'Eastern Cape', 'town', 'Dr Beyers Naudé', 28),
    ('Steytlerville', 'Eastern Cape', 'town', 'Dr Beyers Naudé', 28),
    ('Nieu-Bethesda', 'Eastern Cape', 'town', 'Dr Beyers Naudé', 28),
    ('Willowmore', 'Eastern Cape', 'town', 'Baviaans', 28),
    ('Rietbron', 'Eastern Cape', 'town', 'Baviaans', 30),
    ('Hankey', 'Eastern Cape', 'town', 'Kouga', 22),
    ('Loerie', 'Eastern Cape', 'town', 'Kouga', 26),
    ('Thornhill', 'Eastern Cape', 'town', 'Kouga', 26),
    ('Cape St Francis', 'Eastern Cape', 'town', 'Kouga', 22),
    ('Oyster Bay', 'Eastern Cape', 'town', 'Kouga', 26),
    ('Kareedouw', 'Eastern Cape', 'town', 'Kou-Kamma', 22),
    ('Joubertina', 'Eastern Cape', 'town', 'Kou-Kamma', 24),
    ('Storms River', 'Eastern Cape', 'town', 'Kou-Kamma', 26),
    ('Tsitsikamma', 'Eastern Cape', 'town', 'Kou-Kamma', 26),
    ('Louterwater', 'Eastern Cape', 'town', 'Kou-Kamma', 28),
    ('Clarkson', 'Eastern Cape', 'town', 'Kou-Kamma', 28),
    ('Tsolo', 'Eastern Cape', 'town', 'Mhlontlo', 22),
    ('Qumbu', 'Eastern Cape', 'town', 'Mhlontlo', 22),
    ('Mqanduli', 'Eastern Cape', 'town', 'King Sabata Dalindyebo', 20),
    ('Coffee Bay', 'Eastern Cape', 'town', 'King Sabata Dalindyebo', 22),
    ('Ngqeleni', 'Eastern Cape', 'town', 'Nyandeni', 22),
    ('Nqeleni', 'Eastern Cape', 'town', 'Nyandeni', 22),
    ('Mthatha Central', 'Eastern Cape', 'suburb', 'King Sabata Dalindyebo', 14),
    ('Norwood', 'Eastern Cape', 'suburb', 'King Sabata Dalindyebo', 18),
    ('Southernwood Mthatha', 'Eastern Cape', 'suburb', 'King Sabata Dalindyebo', 18),
    ('Mthatha West', 'Eastern Cape', 'suburb', 'King Sabata Dalindyebo', 18),
    ('Ngangelizwe', 'Eastern Cape', 'suburb', 'King Sabata Dalindyebo', 20),
    ('Zimbane', 'Eastern Cape', 'suburb', 'King Sabata Dalindyebo', 22),
    ('Mvumelwano', 'Eastern Cape', 'suburb', 'King Sabata Dalindyebo', 24),
    ('Mount Frere', 'Eastern Cape', 'town', 'Umzimvubu', 20),
    ('KwaBhaca', 'Eastern Cape', 'town', 'Umzimvubu', 20),
    ('Mount Ayliff', 'Eastern Cape', 'town', 'Umzimvubu', 22),
    ('eMaxesibeni', 'Eastern Cape', 'town', 'Umzimvubu', 22),
    ('Matatiele', 'Eastern Cape', 'town', 'Matatiele', 18),
    ('Cedarville', 'Eastern Cape', 'town', 'Matatiele', 26),
    ('Maluti', 'Eastern Cape', 'town', 'Matatiele', 26),
    ('Tabankulu', 'Eastern Cape', 'town', 'Ntabankulu', 24),
    ('Ntabankulu', 'Eastern Cape', 'town', 'Ntabankulu', 24),
    ('Bizana', 'Eastern Cape', 'town', 'Winnie Madikizela-Mandela', 22),
    ('Mbizana', 'Eastern Cape', 'town', 'Winnie Madikizela-Mandela', 22),
    ('Lusikisiki', 'Eastern Cape', 'town', 'Ingquza Hill', 22),
    ('Holy Cross', 'Eastern Cape', 'town', 'Ingquza Hill', 28),
    ('Lady Grey', 'Eastern Cape', 'town', 'Walter Sisulu', 26),
    ('Rhodes', 'Eastern Cape', 'town', 'Senqu', 30),
    ('Maclear', 'Eastern Cape', 'town', 'Elundini', 24),
    ('Nqanqarhu', 'Eastern Cape', 'town', 'Elundini', 24),
    ('Elliot', 'Eastern Cape', 'town', 'Sakhisizwe', 24),
    ('Khowa', 'Eastern Cape', 'town', 'Sakhisizwe', 24),
    ('Ugie', 'Eastern Cape', 'town', 'Elundini', 26),
    ('Mount Fletcher', 'Eastern Cape', 'town', 'Elundini', 26),
    ('Jamestown', 'Eastern Cape', 'town', 'Walter Sisulu', 28),
    ('Venterstad', 'Eastern Cape', 'town', 'Walter Sisulu', 28),
    ('Steynsburg', 'Eastern Cape', 'town', 'Walter Sisulu', 28),
    ('Molteno', 'Eastern Cape', 'town', 'Enoch Mgijima', 26),
    ('Whittlesea', 'Eastern Cape', 'town', 'Enoch Mgijima', 22),
    ('Tarkastad', 'Eastern Cape', 'town', 'Enoch Mgijima', 24),
    ('Hofmeyr', 'Eastern Cape', 'town', 'Enoch Mgijima', 28),
    ('Sada', 'Eastern Cape', 'suburb', 'Enoch Mgijima', 24),
    ('Ezibeleni', 'Eastern Cape', 'suburb', 'Enoch Mgijima', 22),
    ('Mlungisi', 'Eastern Cape', 'suburb', 'Enoch Mgijima', 22),
    ('Ilinge', 'Eastern Cape', 'suburb', 'Enoch Mgijima', 24),
    ('Engcobo', 'Eastern Cape', 'town', 'Engcobo', 20),
    ('Ngcobo', 'Eastern Cape', 'town', 'Engcobo', 20),
    ('Cala', 'Eastern Cape', 'town', 'Sakhisizwe', 24),
    ('Tsojana', 'Eastern Cape', 'town', 'Sakhisizwe', 28),
    ('Tsombo', 'Eastern Cape', 'town', 'Intsika Yethu', 26),
    ('Tsolo Junction', 'Eastern Cape', 'town', 'Mhlontlo', 28),
    ('Indwe', 'Eastern Cape', 'town', 'Emalahleni', 24),
    ('Dordrecht', 'Eastern Cape', 'town', 'Emalahleni', 24),
    ('Cacadu', 'Eastern Cape', 'town', 'Emalahleni', 26),
    ('Centane', 'Eastern Cape', 'town', 'Mnquma', 22),
    ('Kentani', 'Eastern Cape', 'town', 'Mnquma', 22),
    ('Ngqamakhwe', 'Eastern Cape', 'town', 'Mnquma', 24),
    ('Willowvale', 'Eastern Cape', 'town', 'Mbhashe', 22),
    ('Gatyana', 'Eastern Cape', 'town', 'Mbhashe', 22),
    ('Elliotdale', 'Eastern Cape', 'town', 'Mbhashe', 24),
    ('Xhora', 'Eastern Cape', 'town', 'Mbhashe', 24),
    ('Idutywa', 'Eastern Cape', 'town', 'Mbhashe', 24),
    ('Qhora Mouth', 'Eastern Cape', 'town', 'Mbhashe', 28),
]
