# Generated by Django 6.0.5 on 2026-05-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HelperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='helpers/profile_photos/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('preferred_work_area', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('availability_summary', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('trust_status', models.CharField(choices=[('NEW', 'New'), ('PROFILE_STARTED', 'Profile started'), ('READY_FOR_REVIEW', 'Ready for review'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended')], default='NEW', max_length=24)),
                ('profile_completion_percent', models.PositiveSmallIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelperAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='helpers.helperprofile')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='HelperTrustSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('ID_DOCUMENT', 'ID document'), ('CRIMINAL_RECORD_CHECK', 'Criminal record check'), ('REFERENCES', 'References'), ('EXPERIENCE_CAPTURED', 'Experience captured'), ('PROFILE_PHOTO', 'Profile photo')], max_length=40)),
                ('status', models.CharField(choices=[('NOT_PROVIDED', 'Not provided'), ('READY', 'Ready'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_PROVIDED', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_signals', to='helpers.helperprofile')),
            ],
            options={
                'ordering': ['signal_type'],
            },
        ),
        migrations.CreateModel(
            name='HelperSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('skill_note', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='helpers.helperprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='helper_skills', to='helpers.servicecategory')),
            ],
            options={
                'ordering': ['-is_primary', 'category__sort_order', 'category__name'],
            },
        ),
        migrations.AddIndex(
            model_name='helperprofile',
            index=models.Index(fields=['is_active', 'is_profile_complete'], name='helpers_hel_is_acti_825898_idx'),
        ),
        migrations.AddIndex(
            model_name='helperprofile',
            index=models.Index(fields=['trust_status'], name='helpers_hel_trust_s_1396fc_idx'),
        ),
        migrations.AddIndex(
            model_name='helperprofile',
            index=models.Index(fields=['location'], name='helpers_hel_locatio_02549d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helperavailability',
            unique_together={('helper', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='helpertrustsignal',
            unique_together={('helper', 'signal_type')},
        ),
        migrations.AlterUniqueTogether(
            name='helperskill',
            unique_together={('helper', 'category')},
        ),
    ]
