# Generated by Django 6.0.5 on 2026-05-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
        ('locations', '0001_locality_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='location_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_profiles', to='locations.locality'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='preferred_work_area_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_work_area_profiles', to='locations.locality'),
        ),
    ]
