# Generated by Django 6.0.5 on 2026-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_locality_autocomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='helpers/profile_photos/%Y/%m/'),
        ),
    ]
