# Generated by Django 6.0.5 on 2026-05-30 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_profile_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_DOCUMENT', 'ID document'), ('CRIMINAL_RECORD_CHECK', 'Criminal record check')], max_length=40)),
                ('file', models.FileField(upload_to='helpers/verification/%Y/%m/')),
                ('status', models.CharField(choices=[('NOT_UPLOADED', 'Not uploaded'), ('UPLOADED', 'Uploaded'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='helpers.helperprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['helper', 'document_type', 'is_current'], name='helpers_wor_helper__3991ba_idx'), models.Index(fields=['status'], name='helpers_wor_status_1cb7e1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('helper', 'document_type'), name='unique_current_worker_verification_document')],
            },
        ),
    ]
