# Generated by Django 6.0.5 on 2026-05-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_1fa9a5_idx',
            old_name='accounts_us_role_91c18a_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_phone_n_613c4a_idx',
            old_name='accounts_us_phone_n_21d2e7_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_is_onbo_36f375_idx',
            old_name='accounts_us_is_onbo_4c8be8_idx',
        ),
    ]
