# Generated by Django 6.0.5 on 2026-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_optional_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile_photos/%Y/%m/'),
        ),
    ]
