# Generated by Django 6.0.5 on 2026-05-10 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerOnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_location', models.CharField(blank=True, max_length=255)),
                ('service_type', models.CharField(blank=True, choices=[('once_off_cleaning', 'Once-off cleaning'), ('recurring_help', 'Recurring help'), ('office_cleaning', 'Office cleaning'), ('laundry', 'Laundry'), ('cooking', 'Cooking'), ('childcare', 'Childcare')], max_length=40)),
                ('service_frequency', models.CharField(blank=True, choices=[('once_off', 'Once-off'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('as_needed', 'As needed')], max_length=30)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelperOnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('selected_categories', models.TextField(blank=True)),
                ('has_id_document_ready', models.BooleanField(blank=True, null=True)),
                ('has_criminal_check_ready', models.BooleanField(blank=True, null=True)),
                ('has_references', models.BooleanField(blank=True, null=True)),
                ('preferred_work_area', models.CharField(blank=True, max_length=255)),
                ('availability_summary', models.CharField(blank=True, max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
