# Generated by Django 6.0.5 on 2026-05-29 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_locality_autocomplete'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeronboardingprofile',
            name='preferred_location_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_onboarding_locations', to='locations.locality'),
        ),
        migrations.AddField(
            model_name='helperonboardingprofile',
            name='location_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_onboarding_locations', to='locations.locality'),
        ),
        migrations.AddField(
            model_name='helperonboardingprofile',
            name='preferred_work_area_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_onboarding_work_areas', to='locations.locality'),
        ),
    ]
