# Generated by Django 6.0.5 on 2026-05-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('province', models.CharField(max_length=80)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('locality_type', models.CharField(choices=[('suburb', 'Suburb'), ('city', 'City'), ('town', 'Town')], default='suburb', max_length=20)),
                ('search_text', models.CharField(blank=True, db_index=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'localities',
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['is_active', 'name'], name='locations_l_is_acti_f06511_idx'), models.Index(fields=['is_active', 'province'], name='locations_l_is_acti_6b0a46_idx')],
            },
        ),
    ]
