# Generated by Django 6.0.5 on 2026-05-10 20:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('helpers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_WORKER_RESPONSE', 'Pending worker response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED_BY_EMPLOYER', 'Cancelled by employer'), ('CANCELLED_BY_WORKER', 'Cancelled by worker'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CLOSED', 'Closed')], default='PENDING_WORKER_RESPONSE', max_length=32)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('special_instructions', models.TextField(blank=True)),
                ('worker_fee_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_fee_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='employers.employerprofile')),
                ('employer_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='employers.employerlocation')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='helpers.servicecategory')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='helpers.helperprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REQUEST_CREATED', 'Request created'), ('WORKER_ACCEPTED', 'Worker accepted'), ('WORKER_DECLINED', 'Worker declined'), ('EMPLOYER_CANCELLED', 'Employer cancelled'), ('WORKER_CANCELLED', 'Worker cancelled'), ('MARKED_COMPLETED', 'Marked completed'), ('STATUS_CHANGED', 'Status changed'), ('NOTE_ADDED', 'Note added')], max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bookings.booking')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_events_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'scheduled_date'], name='bookings_bo_status_b26418_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['employer', 'status'], name='bookings_bo_employe_ed7cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['worker', 'status'], name='bookings_bo_worker__24db45_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingevent',
            index=models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_d5ff0d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingevent',
            index=models.Index(fields=['event_type'], name='bookings_bo_event_t_b06c97_idx'),
        ),
    ]
