# Generated by Django 6.0.5 on 2026-05-12 05:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='request_type',
            field=models.CharField(choices=[('DIRECT_REQUEST', 'Direct request'), ('OPEN_MARKETPLACE', 'Open marketplace')], default='DIRECT_REQUEST', max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN_FOR_APPLICATIONS', 'Open for applications'), ('APPLICATIONS_RECEIVED', 'Applications received'), ('WORKER_SELECTED', 'Worker selected'), ('PENDING_WORKER_RESPONSE', 'Pending worker response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED_BY_EMPLOYER', 'Cancelled by employer'), ('CANCELLED_BY_WORKER', 'Cancelled by worker'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CLOSED', 'Closed')], default='PENDING_WORKER_RESPONSE', max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='helpers.helperprofile'),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='event_type',
            field=models.CharField(choices=[('REQUEST_CREATED', 'Request created'), ('WORKER_ACCEPTED', 'Worker accepted'), ('WORKER_DECLINED', 'Worker declined'), ('EMPLOYER_CANCELLED', 'Employer cancelled'), ('WORKER_CANCELLED', 'Worker cancelled'), ('MARKED_COMPLETED', 'Marked completed'), ('MARKETPLACE_JOB_POSTED', 'Marketplace job posted'), ('WORKER_APPLIED', 'Worker applied'), ('WORKER_WITHDREW_APPLICATION', 'Worker withdrew application'), ('EMPLOYER_SELECTED_APPLICANT', 'Employer selected applicant'), ('APPLICATION_DECLINED', 'Application declined'), ('STATUS_CHANGED', 'Status changed'), ('NOTE_ADDED', 'Note added')], max_length=32),
        ),
        migrations.CreateModel(
            name='BookingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('WITHDRAWN', 'Withdrawn'), ('DECLINED', 'Declined')], default='PENDING', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('proposed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='bookings.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_applications', to='helpers.helperprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='bookings_bo_booking_6d19b6_idx'), models.Index(fields=['worker', 'status'], name='bookings_bo_worker__8dc3d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'worker'), name='unique_booking_application_per_worker')],
            },
        ),
    ]
